# Generated by https://quicktype.io

from typing import List


class Age:
    name: int
    accuracy: float

    def __init__(self, name: int, accuracy: float) -> None:
        self.name = name
        self.accuracy = accuracy


class Gender:
    name: str
    accuracy: float

    def __init__(self, name: str, accuracy: float) -> None:
        self.name = name
        self.accuracy = accuracy


class Point:
    x: int
    y: int

    def __init__(self, x: int, y: int) -> None:
        self.x = x
        self.y = y


class People:
    id: int
    points: List[Point]
    is_out_line: bool
    is_in_line: bool
    is_center_line: bool
    age: Age
    gender: Gender

    def __init__(self, id: int, points: List[Point], is_out_line: bool, is_in_line: bool, is_center_line: bool,
                 age: Age, gender: Gender) -> None:
        self.id = id
        self.points = points
        self.is_out_line = is_out_line
        self.is_in_line = is_in_line
        self.is_center_line = is_center_line
        self.age = age
        self.gender = gender


class PeopleList:
    peoples: List[People]

    def __init__(self, peoples: List[People]) -> None:
        self.peoples = peoples
